### ISSUE TITLE
StarGeometry compilation fail

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#258] opened 2021-12-17 04:46 UTC
PR #202 broke the DEV [AutoBuild](https://www.star.bnl.gov/public/comp/prod/Sanity/AutoBuild.html) tonight:
```
.sl73_gcc485/OBJ/StarVMC/StarGeometry/BbcmGeo.cxx: In member function 'virtual void BBCMGEO::BPOL::Block(AgCreate)':
.sl73_gcc485/OBJ/StarVMC/StarGeometry/BbcmGeo.cxx:516:33: error: 'class AgModule' has no member named 'AddCut'
                       module()-&gt;AddCut(active()-&gt;GetName(),"cutgam",0.00008);           
                                 ^
.sl73_gcc485/OBJ/StarVMC/StarGeometry/BbcmGeo.cxx:517:33: error: 'class AgModule' has no member named 'AddCut'
                       module()-&gt;AddCut(active()-&gt;GetName(),"cutele",0.001);           
                                 ^
...
```

**Comment by klendathu2k** [comment] 2021-12-17 14:24
Suspect that cons lacks a rule to update XML --> .cxx when the parser changes.  
Try

rm  .sl73_gcc485/OBJ/StarVMC/StarGeometry/*

and rebuild.

**Comment by genevb** [comment] 2021-12-17 15:44
Nope. I tried that and got both the same error as last night, and the files you had me remove were not re-built (that directory [both obj and OBJ] is now empty after the attempted build).

-Gene

**Comment by genevb** [comment] 2021-12-17 15:57
Actually, it wasn't exactly the same error this time. Instead of "AddCut", it's complaining about "AddHit" over and over now....

/afs/rhic.bnl.gov/star/packages/gitdev/.sl73_gcc485/obj/StarVMC/StarGeometry/EiddGeo.cxx: In member function 'virtual void EIDDGEO::TGAP::Block(AgCreate)':
/afs/rhic.bnl.gov/star/packages/gitdev/.sl73_gcc485/obj/StarVMC/StarGeometry/EiddGeo.cxx:792:33: error: 'class AgModule' has no member named 'AddHit'
                       module()-&gt;AddHit( "TGAP", "z", 0.0005, 0, 0, "s");           
                                 ^
/afs/rhic.bnl.gov/star/packages/gitdev/.sl73_gcc485/obj/StarVMC/StarGeometry/EiddGeo.cxx:793:33: error: 'class AgModule' has no member named 'AddHit'
                       module()-&gt;AddHit( "TGAP", "y", 0.0005, 0, 0, "");           
                                 ^
...

**Comment by klendathu2k** [comment] 2021-12-17 16:46
I can reproduce this in a local build.  There is something odd going on 
here...  investigating.

**Comment by klendathu2k** [comment] 2021-12-17 17:15
I think that cons is getting confused, and mixing in the .h and .cxx 
files from $STAR, instead of
building them from the XML files.


The following works --

setup 32b
starver dev
setenv STAR .
cons +StarVMC/Geometry
cons +StarVMC/StarGeometry
cons +StarVMC/xgeometry

Jason

**Comment by genevb** [comment] 2021-12-17 20:02
AutoBuild succeeded with these instructions. Thanks, Jason.

Should this issue remain open until this issue is resolved in cons for the next time, or should we close the issue? I have no preference.

-Gene

**Comment by klendathu2k** [comment] 2021-12-17 21:00
I say keep it open until the next successful autobuild.

**Comment by plexoos** [comment] 2021-12-18 17:02
@veprbl proposed a patch (#261) that is likely to fix this issue. In the original PR #202 Jason modified mgr/Dyson/Export/AgROOT.py, a script that generates c++ code from the xml files. In this case, Cons was supposed to regenerate the c++ code just like when the xml files are modified but such dependency was not established directly. This fix creates the missing dependency on the parser scripts.

We don't see this kind of problems in CI builds because the entire code is built from scratch every time in an empty .sl##_gcc### directory. The errors from AutoBuild suggest that the build was likely performed with an existing .sl##_gcc### directory and not all sources were properly regenerated.

I don't expect any side effects from #261 and suggest we accept it

**Comment by genevb** [comment] 2021-12-18 19:41
Yes: AutoBuild has always been an incremental build, not a build from scratch.

-Gene

On Dec 18, 2021, at 12:02 PM, Dmitri Smirnov ***@***.******@***.***>> wrote:

We don't see this kind of problems in CI builds because the entire code is built from scratch every time in an empty .sl##_gcc### directory. The errors from AutoBuild suggest that the build was likely performed with an existing .sl##_gcc### directory and not all sources were properly regenerated.

**Comment by plexoos** [comment] 2021-12-18 22:03
It shouldn't matter for a properly configured build system. Similarly, the value of $STAR should not affect the build of the entire source code checked out locally. This issue seems to expose an oversight in Cons which may be fixed with the patch.

**Closed as completed** 2021-12-20 17:19 UTC
